const fs = require('fs');
const path = require('path');

const AUDITS_DIR = path.join(__dirname, '../../.audits/audits');

function getAuditLogPaths(prefix, name) {
  const logFile = path.join(AUDITS_DIR, `${prefix}-${name}-violations.log`);
  const filesLogFile = path.join(AUDITS_DIR, `${prefix}-${name}-files.log`);
  return { logFile, filesLogFile };
}


function deduplicate(violations) {
  const seen = new Set();
  return violations.filter(v => {
    const key = `${v.location}|${v.details}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function groupViolationsByFile(violations) {
  const grouped = {};
  violations.forEach(v => {
    const [filePath, lineNum] = v.location.split(':');
    if (!grouped[filePath]) grouped[filePath] = [];
    grouped[filePath].push({ lineNum: lineNum || '', details: v.details });
  });
  return grouped;
}

function cleanFilesLog(filesLogFile) {
  if (fs.existsSync(filesLogFile)) {
    try { fs.unlinkSync(filesLogFile); } catch (_) {}
  }
}

function generateReportHeader(auditName, timestamp) {
  return "/*\n" +
    "  ===================================================================\n" +
    "  AGENT INSTRUCTION PROMPT (Copy/Paste for AI Agent)\n" +
    "  ===================================================================\n" +
    "  TASK: Analyze and resolve the findings listed in this audit log file.\n" +
    "\n" +
    "  INSTRUCTIONS FOR AGENT:\n" +
    "  1. Review all listed target files and issue descriptions below.\n" +
    "  2. Validate each finding against true code quality & performance standards (filter out false positives if any).\n" +
    "  3. Execute required refactorings or fixes to resolve legitimate findings.\n" +
    "  4. Verify that code changes preserve application behavior and pass test/audit suites.\n" +
    "  ===================================================================\n" +
    "  DOCUMENT DESCRIPTION:\n" +
    `  This document contains automated audit findings for: ${auditName.toUpperCase()}.\n` +
    "  It serves as an issue log generated by the .tools system auditors to track codebase health.\n" +
    "  ===================================================================\n" +
    "*/\n\n" +
    "===================================================================\n" +
    `               ${auditName.toUpperCase()} REPORT                            \n` +
    "Timestamp: " + (timestamp || new Date().toISOString()) + "\n" +
    "===================================================================\n\n";
}

function formatGroupedViolations(grouped) {
  let body = "";
  Object.entries(grouped).forEach(([filePath, items]) => {
    body += `File: ${filePath}\n`;
    items.forEach((item) => {
      const lineStr = item.lineNum ? `L${item.lineNum}` : '';
      body += `  ${lineStr.padEnd(6)} ${item.details}\n`;
    });
    body += `\n`;
  });
  return body;
}

function writeFilesSummaryReport(filesLogFile, fileCount, violationsCount, grouped, timestamp) {
  let filesReport = generateReportHeader("FILES WITH ISSUES", timestamp);
  filesReport += `Found ${violationsCount} issue(s) across ${fileCount} target(s):\n\n`;
  Object.keys(grouped).forEach(filePath => {
    filesReport += `- ${filePath} (${grouped[filePath].length} issues)\n`;
  });
  fs.writeFileSync(filesLogFile, filesReport);
  console.log("  -> Also generated compact file list: " + path.basename(filesLogFile));
}

function cleanupEmptyLogs(logFile, filesLogFile) {
  cleanFilesLog(filesLogFile);
  if (fs.existsSync(logFile)) {
    try { fs.unlinkSync(logFile); } catch (_) {}
  }
  const logDir = path.dirname(logFile);
  if (fs.existsSync(logDir)) {
    try {
      const files = fs.readdirSync(logDir);
      if (files.length === 0) {
        fs.rmdirSync(logDir);
      }
    } catch (_) {}
  }
}

function writeAuditReport({ violations, logFile, filesLogFile, auditName, issueTypeName, timestamp }) {
  if (violations.length === 0) {
    cleanupEmptyLogs(logFile, filesLogFile);
    console.log(`[${auditName}] Finished (0 unique issues) -> Clean`);
    return;
  }

  const grouped = groupViolationsByFile(violations);
  const fileCount = Object.keys(grouped).length;

  let report = generateReportHeader(auditName, timestamp);
  report += `Found ${violations.length} ${issueTypeName} issue(s) across ${fileCount} file(s):\n\n`;
  report += formatGroupedViolations(grouped);

  const logDir = path.dirname(logFile);
  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir, { recursive: true });
  }

  if (fileCount > 10) {
    writeFilesSummaryReport(filesLogFile, fileCount, violations.length, grouped, timestamp);
  } else {
    cleanFilesLog(filesLogFile);
  }

  fs.writeFileSync(logFile, report);
  console.log(`[${auditName}] Finished (${violations.length} unique issues) -> ${path.relative(path.join(__dirname, '../..'), logFile)}`);
}

function walkDir(dirPath, callback) {
  if (!fs.existsSync(dirPath)) return;
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      walkDir(fullPath, callback);
    } else if (entry.isFile() && /\.(js|jsx|ts|tsx)$/.test(entry.name)) {
      callback(fullPath);
    }
  }
}

function getAllFiles(dir, fileList = [], rootDir = path.join(__dirname, '../..')) {
  if (!fs.existsSync(dir)) return fileList;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      getAllFiles(fullPath, fileList, rootDir);
    } else if (/\.(js|jsx|ts|tsx)$/.test(entry.name)) {
      const relPath = path.relative(rootDir, fullPath).replace(/\\/g, '/');
      fileList.push({ relPath, fullPath, content: fs.readFileSync(fullPath, 'utf8') });
    }
  }
  return fileList;
}

function getFileLines(filePath) {
  const relPath = path.relative(path.join(__dirname, '../..'), filePath).replace(/\\/g, '/');
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  return { relPath, content, lines };
}

function scanFileLines(filePath, violations, lineChecker) {
  const { relPath, lines } = getFileLines(filePath);
  lines.forEach((line, index) => {
    lineChecker(line, index, relPath, violations);
  });
}

function isCommentLine(line) {
  const trimmed = line.trim();
  return trimmed.startsWith('//') || trimmed.startsWith('*');
}

function finishAuditReport({ auditName, disableDynamicAudits, violations, logFile, filesLogFile, issueTypeName }) {
  if (disableDynamicAudits) {
    console.log(`[${auditName}] Skipped (dynamic audits disabled)`);
    return;
  }
  const timestamp = new Date().toLocaleString('ru-RU');
  writeAuditReport({
    violations,
    logFile,
    filesLogFile,
    auditName,
    issueTypeName,
    timestamp
  });
}

function runAuditorScan({ auditName, disableDynamicAudits, logFile, filesLogFile, issueTypeName, scanFile, srcDir = path.resolve(__dirname, '../../../src'), auditsDir = path.join(__dirname, '../../.audits/audits') }) {
  if (!fs.existsSync(auditsDir)) fs.mkdirSync(auditsDir, { recursive: true });
  const rawViolations = [];
  walkDir(srcDir, (filePath) => scanFile(filePath, rawViolations));
  const violations = deduplicate(rawViolations);

  finishAuditReport({
    auditName,
    disableDynamicAudits,
    violations,
    logFile,
    filesLogFile,
    issueTypeName
  });
}

module.exports = {
  getAuditLogPaths,
  deduplicate,
  writeAuditReport,
  walkDir,
  getAllFiles,
  getFileLines,
  scanFileLines,
  isCommentLine,
  finishAuditReport,
  runAuditorScan
};

