const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { shouldScanSubdirectories } = require('./manifestSettings');

function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function readdirRecursiveSync(dir, baseDir = dir) {
  let results = [];
  if (!fs.existsSync(dir)) return results;
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(readdirRecursiveSync(filePath, baseDir));
    } else if (stat && stat.isFile()) {
      const relativePath = path.relative(baseDir, filePath).replace(/\\/g, '/');
      results.push(relativePath);
    }
  });
  return results;
}

const MEDIA_ROOT = path.join(__dirname, '..', 'media');
const MANIFEST_JS_PATH = path.join(__dirname, '..', 'src', 'media', 'mediaManifest.js');
const MANIFEST_JSON_PATH = path.join(MEDIA_ROOT, 'media-manifest.json');

const SUPPORTED_EXTENSIONS = {
  images: ['jpg', 'jpeg', 'png', 'webp', 'svg'],
  gifs:   ['gif'],
  videos: ['mp4', 'webm'],
};

function filterByCategory(category, dirPath, scanSubdirectories) {
  const allowedExts = SUPPORTED_EXTENSIONS[category] || [];
  
  if (scanSubdirectories) {
    const allFiles = readdirRecursiveSync(dirPath);
    return allFiles.filter(file => {
      const ext = path.extname(file).slice(1).toLowerCase();
      return allowedExts.includes(ext);
    });
  }

  const files = fs.readdirSync(dirPath);
  return files.filter(file => {
    const filePath = path.join(dirPath, file);
    if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
      const ext = path.extname(file).slice(1).toLowerCase();
      return allowedExts.includes(ext);
    }
    return false;
  });
}

function scanCategory(category, scanSubdirectories) {
  const dirPath = path.join(MEDIA_ROOT, category);
  if (!fs.existsSync(dirPath)) {
    console.warn(`⚠️ Directory does not exist: ${dirPath}. Creating it.`);
    fs.mkdirSync(dirPath, { recursive: true });
    return [];
  }

  const matchedFiles = filterByCategory(category, dirPath, scanSubdirectories);
  matchedFiles.sort();
  console.log(`📁 ${category}: found ${matchedFiles.length} file(s)`);
  return matchedFiles;
}

function scanMedia(scanSubdirectories) {
  return {
    images: scanCategory('images', scanSubdirectories),
    gifs: scanCategory('gifs', scanSubdirectories),
    videos: scanCategory('videos', scanSubdirectories),
  };
}

function getJsContent(manifestData) {
  return `/**
 * mediaManifest.js
 *
 * Static index of files present in the local media folders.
 * Generated automatically by running \`npm run generate-media\`.
 * Do not edit this file manually.
 *
 * Structure: { category: [fileName, ...] }
 */
import { MEDIA_CATEGORY } from './mediaTypes';

const mediaManifest = {
  [MEDIA_CATEGORY.IMAGES]: [
${manifestData.images.map(name => `    '${name}',`).join('\n')}
  ],
  [MEDIA_CATEGORY.GIFS]: [
${manifestData.gifs.map(name => `    '${name}',`).join('\n')}
  ],
  [MEDIA_CATEGORY.VIDEOS]: [
${manifestData.videos.map(name => `    '${name}',`).join('\n')}
  ],
  regenerated: true,
  generatedAt: ${Date.now()},
};

export default mediaManifest;
`;
}

function writeManifestFiles(manifestData) {
  const jsContent = getJsContent(manifestData);
  const jsonContent = JSON.stringify({
    images: manifestData.images,
    gifs: manifestData.gifs,
    videos: manifestData.videos,
    regenerated: true,
    generatedAt: Date.now(),
  }, null, 2);

  fs.writeFileSync(MANIFEST_JS_PATH, jsContent, 'utf8');
  console.log(`✨ Successfully generated JS manifest at ${MANIFEST_JS_PATH}`);

  fs.writeFileSync(MANIFEST_JSON_PATH, jsonContent, 'utf8');
  console.log(`✨ Successfully generated JSON manifest at ${MANIFEST_JSON_PATH}`);
}

function runWebExport() {
  console.log('📦 Running web export...');
  try {
    execSync('npx expo export --platform web', { stdio: 'inherit', shell: true });
    console.log('✨ Web export completed successfully.');
  } catch (err) {
    console.error('❌ Web export failed:', err.message);
    process.exit(1);
  }
}

function copyMediaToDist() {
  console.log('📁 Copying media directory to dist/media...');
  try {
    const srcDir = MEDIA_ROOT;
    const destDir = path.join(__dirname, '..', 'dist', 'media');
    copyDirSync(srcDir, destDir);
    console.log('✨ Media directory copied successfully.');
  } catch (err) {
    console.error('❌ Failed to copy media directory:', err.message);
    process.exit(1);
  }
}

function generateManifest() {
  console.log('🔍 Scanning media folders...');
  const scanSubdirectories = shouldScanSubdirectories();
  if (scanSubdirectories) {
    console.log('📂 Recursive scanning is enabled.');
  }

  const manifestData = scanMedia(scanSubdirectories);
  writeManifestFiles(manifestData);
  runWebExport();
  copyMediaToDist();
}

generateManifest();
