import { StyleSheet } from 'react-native';
import { colors, layout } from '../../../theme/tokens';
import { shadow } from '../../../theme/shadows';

export default StyleSheet.create({
  container: {
    padding: 24,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  toolbarTitle: {
    flex: 1,
    color: colors.secondaryLightText,
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 44,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: colors.neutralLightFaint,
    borderWidth: 1,
    borderColor: colors.inputBorderLight,
  },
  resetBtnText: {
    color: colors.neutralDarkStrong,
  },
  card: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 20,
    ...shadow.card(),
    elevation: 2,
    marginBottom: 24,
    gap: 20,
  },
  bannerRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutralLightFaint,
  },
  previewContainer: {
    width: 140,
    minHeight: 90,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: colors.neutralLightFaint,
    borderWidth: 1,
    borderColor: colors.inputBorderLight,
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  noImage: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noImageText: {
    color: colors.textSubtleLight,
    textAlign: 'center',
  },
  actionsCol: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 10,
  },
  uploadBtn: {
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: colors.dark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadBtnText: {
    color: colors.white,
  },
  deleteBtn: {
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtnText: {
    color: colors.white,
  },

  /* In-app delete confirmation modal */
  confirmOverlay: {
    flex: 1,
    backgroundColor: colors.overlayScrim,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: layout.zIndices.modal,
  },
  confirmCard: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 24,
    ...shadow.modal(),
    elevation: 10,
  },
  confirmTitle: {
    color: colors.dark,
    marginBottom: 8,
  },
  confirmMsg: {
    color: colors.slateText,
    marginBottom: 20,
  },
  confirmRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelBtn: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    backgroundColor: colors.secondaryLightBg,
    borderWidth: 1,
    borderColor: colors.secondaryLightBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    color: colors.secondaryLightText,
  },
  confirmDeleteBtn: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmDeleteBtnText: {
    color: colors.white,
  },
  /* Desktop grid & cards */
  desktopGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  bannerCardDesktop: {
    width: 260,
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.secondaryLightBorder,
    gap: 14,
    ...shadow.card(),
    elevation: 2,
  },
  previewContainerDesktop: {
    width: '100%',
    height: 140,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: colors.neutralLightFaint,
    borderWidth: 1,
    borderColor: colors.inputBorderLight,
  },
  addCardDesktop: {
    width: 260,
    minHeight: 250,
    backgroundColor: colors.surfaceNeutralLight,
    borderRadius: 14,
    padding: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: colors.slateStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addCardBtnText: {
    color: colors.secondaryLightText,
  },
  addBtn: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.textSubtleLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  addBtnText: {
    color: colors.neutralDarkStrong,
  },
  saveBtn: {
    height: 40,
    paddingHorizontal: 24,
    borderRadius: 8,
    backgroundColor: colors.dark,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: {
    color: colors.white,
  },
});
