/**
 * mediaService.js
 *
 * Media discovery service.
 * Returns lists of available media assets grouped by category.
 * Supports both local static manifest and live Cloudinary asset synchronization.
 */
import { MEDIA_CATEGORY, createMediaItem } from './mediaTypes.js';
import mediaManifest from './mediaManifest.js';
import { isValidMediaItem } from './mediaValidation.js';
import { CloudinaryStorageProvider } from '../services/storage/providers/cloudinaryStorageProvider.js';
import mediaPoolData from '../constants/mediaPool.json' with { type: 'json' };

const cloudinaryProvider = new CloudinaryStorageProvider();

const VIDEO_EXTENSIONS = ['mp4', 'webm', 'mov', 'mkv', 'avi'];
const GIF_EXTENSIONS = ['gif'];

/**
 * Returns true if the manifest has been generated by `npm run generate-media`.
 * @returns {boolean}
 */
export function isManifestGenerated() {
  return mediaManifest.regenerated === true;
}

/**
 * Returns all local MediaItems for a given category.
 * @param {string} category
 * @returns {object[]}
 */
function listLocalByCategory(category) {
  const fileNames = mediaManifest[category] ?? [];
  return fileNames
    .map((name) => createMediaItem(category, name))
    .filter(isValidMediaItem);
}

/**
 * Returns all available local media assets grouped by category.
 * @returns {{ images: object[], gifs: object[], videos: object[] }}
 */
export function listAllMedia() {
  return {
    images: listLocalByCategory(MEDIA_CATEGORY.IMAGES),
    gifs:   listLocalByCategory(MEDIA_CATEGORY.GIFS),
    videos: listLocalByCategory(MEDIA_CATEGORY.VIDEOS),
  };
}

/**
 * Asynchronously fetches and categorizes live media assets from Cloudinary.
 * Tries local proxy first, then direct provider list, and falls back to mediaPool.json.
 *
 * @returns {Promise<{ images: object[], gifs: object[], videos: object[] }>}
 */
export async function fetchLiveMediaList() {
  // 1. Try local dev-server proxy endpoint
  try {
    const controller = typeof AbortController !== 'undefined' ? new AbortController() : null;
    const timeoutId = controller ? setTimeout(() => controller.abort(), 2000) : null;
    const proxyRes = await fetch('http://localhost:8082/api/cloudinary/resources', {
      signal: controller?.signal,
    });
    if (timeoutId) clearTimeout(timeoutId);
    if (proxyRes.ok) {
      const proxyData = await proxyRes.json();
      if (proxyData && (proxyData.images?.length || proxyData.videos?.length || proxyData.gifs?.length)) {
        return {
          images: (proxyData.images || []).filter(isValidMediaItem),
          gifs:   (proxyData.gifs || []).filter(isValidMediaItem),
          videos: (proxyData.videos || []).filter(isValidMediaItem),
        };
      }
    }
  } catch (err) {
    // Dev proxy unreachable, continue to direct / pool fallback
  }

  // 2. Try direct provider list
  try {
    const [imageResources, videoResources] = await Promise.all([
      cloudinaryProvider.listResources('image'),
      cloudinaryProvider.listResources('video'),
    ]);

    const allResources = [...imageResources, ...videoResources];

    if (allResources.length > 0) {
      const images = allResources.filter((r) => r.category === MEDIA_CATEGORY.IMAGES && isValidMediaItem(r));
      const gifs = allResources.filter((r) => r.category === MEDIA_CATEGORY.GIFS && isValidMediaItem(r));
      const videos = allResources.filter((r) => r.category === MEDIA_CATEGORY.VIDEOS && isValidMediaItem(r));

      return { images, gifs, videos };
    }
  } catch (err) {
    // Fall back to pool
  }

  // 3. Fallback to centralized mediaPoolData
  const poolUrls = [
    ...(mediaPoolData.images || []),
    ...(mediaPoolData.categoryImages || []),
    ...(mediaPoolData.productImages || []),
    ...(mediaPoolData.banners || []),
    ...(mediaPoolData.gifs || []),
    ...(mediaPoolData.videos || []),
  ];
  const uniquePoolUrls = [...new Set(poolUrls)];

  if (uniquePoolUrls.length > 0) {
    const images = [];
    const gifs = [];
    const videos = [];

    uniquePoolUrls.forEach((url) => {
      const cleanUrl = url.split('?')[0].split('#')[0];
      const ext = (cleanUrl.split('.').pop() || '').toLowerCase();
      const rawName = cleanUrl.split('/').pop() || 'asset';
      const isGif = GIF_EXTENSIONS.includes(ext);
      const isVideo = VIDEO_EXTENSIONS.includes(ext) || url.includes('/video/upload/');
      const category = isVideo ? MEDIA_CATEGORY.VIDEOS : (isGif ? MEDIA_CATEGORY.GIFS : MEDIA_CATEGORY.IMAGES);
      const type = isVideo ? 'video' : (isGif ? 'gif' : 'image');

      const item = {
        id: url,
        name: rawName,
        path: url,
        url,
        type,
        category,
      };

      if (isValidMediaItem(item)) {
        if (category === MEDIA_CATEGORY.VIDEOS) videos.push(item);
        else if (category === MEDIA_CATEGORY.GIFS) gifs.push(item);
        else images.push(item);
      }
    });

    return { images, gifs, videos };
  }

  return listAllMedia();
}
