/**
 * mediaService.js
 *
 * Media discovery service.
 * Returns lists of available media assets grouped by category.
 * Supports both local static manifest and live Cloudinary asset synchronization.
 */
import { MEDIA_CATEGORY, createMediaItem } from './mediaTypes';
import mediaManifest from './mediaManifest';
import { isValidMediaItem } from './mediaValidation';
import { CloudinaryStorageProvider } from '../services/storage/providers/cloudinaryStorageProvider';
import mediaPoolData from '../constants/mediaPool.json' with { type: 'json' };

const cloudinaryProvider = new CloudinaryStorageProvider();

/**
 * Returns true if the manifest has been generated by `npm run generate-media`.
 * @returns {boolean}
 */
export function isManifestGenerated() {
  return mediaManifest.regenerated === true;
}

/**
 * Returns all local MediaItems for a given category.
 * @param {string} category
 * @returns {object[]}
 */
function listLocalByCategory(category) {
  const fileNames = mediaManifest[category] ?? [];
  return fileNames
    .map((name) => createMediaItem(category, name))
    .filter(isValidMediaItem);
}

/**
 * Returns all available local media assets grouped by category.
 * @returns {{ images: object[], gifs: object[], videos: object[] }}
 */
export function listAllMedia() {
  return {
    images: listLocalByCategory(MEDIA_CATEGORY.IMAGES),
    gifs:   listLocalByCategory(MEDIA_CATEGORY.GIFS),
    videos: listLocalByCategory(MEDIA_CATEGORY.VIDEOS),
  };
}

/**
 * Asynchronously fetches and categorizes live media assets from Cloudinary.
 * Falls back to local mediaPool.json and static manifest when offline or unavailable.
 *
 * @returns {Promise<{ images: object[], gifs: object[], videos: object[] }>}
 */
export async function fetchLiveMediaList() {
  try {
    const [imageResources, videoResources] = await Promise.all([
      cloudinaryProvider.listResources('image'),
      cloudinaryProvider.listResources('video'),
    ]);

    const allResources = [...imageResources, ...videoResources];

    if (allResources.length > 0) {
      const images = allResources.filter((r) => r.category === MEDIA_CATEGORY.IMAGES && isValidMediaItem(r));
      const gifs = allResources.filter((r) => r.category === MEDIA_CATEGORY.GIFS && isValidMediaItem(r));
      const videos = allResources.filter((r) => r.category === MEDIA_CATEGORY.VIDEOS && isValidMediaItem(r));

      return { images, gifs, videos };
    }
  } catch (err) {
    // Graceful fallback to pool/manifest
  }

  const poolUrls = [
    ...(mediaPoolData.categoryImages || []),
    ...(mediaPoolData.productImages || []),
    ...(mediaPoolData.banners || []),
  ];
  const uniquePoolUrls = [...new Set(poolUrls)];

  if (uniquePoolUrls.length > 0) {
    const images = [];
    const gifs = [];
    const videos = [];

    uniquePoolUrls.forEach((url) => {
      const ext = (url.split('.').pop() || '').toLowerCase();
      const rawName = url.split('/').pop() || 'asset';
      const isGif = ext === 'gif';
      const isVideo = ext === 'mp4' || ext === 'webm';
      const category = isVideo ? MEDIA_CATEGORY.VIDEOS : (isGif ? MEDIA_CATEGORY.GIFS : MEDIA_CATEGORY.IMAGES);
      const type = isVideo ? 'video' : (isGif ? 'gif' : 'image');

      const item = {
        id: url,
        name: rawName,
        path: url,
        url,
        type,
        category,
      };

      if (isValidMediaItem(item)) {
        if (category === MEDIA_CATEGORY.VIDEOS) videos.push(item);
        else if (category === MEDIA_CATEGORY.GIFS) gifs.push(item);
        else images.push(item);
      }
    });

    return { images, gifs, videos };
  }

  return listAllMedia();
}
