/**
 * mediaService.js
 *
 * Media discovery service.
 * Returns lists of available local media assets grouped by category.
 *
 * In the browser, we cannot scan the filesystem directly, so discovery
 * is driven by the static manifest (mediaManifest.js).
 *
 * Run `npm run generate-media` to regenerate the manifest from disk.
 * Metro Fast Refresh will auto-update the browser after regeneration.
 */
import { MEDIA_CATEGORY, createMediaItem } from './mediaTypes';
import mediaManifest from './mediaManifest';
import { isValidMediaItem } from './mediaValidation';

/**
 * Returns true if the manifest has been generated by `npm run generate-media`.
 * Returns false when the manifest is the initial un-generated template.
 * @returns {boolean}
 */
export function isManifestGenerated() {
  return mediaManifest.regenerated === true;
}

/**
 * Returns all MediaItems for a given category.
 * Items that fail validation (unsupported extension or missing fields) are excluded.
 *
 * @param {string} category - One of MEDIA_CATEGORY values.
 * @returns {object[]} Array of MediaItem
 */
function listByCategory(category) {
  const fileNames = mediaManifest[category] ?? [];
  return fileNames
    .map((name) => createMediaItem(category, name))
    .filter(isValidMediaItem);
}

/** @returns {object[]} */
function listImages() {
  return listByCategory(MEDIA_CATEGORY.IMAGES);
}

/** @returns {object[]} */
function listGifs() {
  return listByCategory(MEDIA_CATEGORY.GIFS);
}

/** @returns {object[]} */
function listVideos() {
  return listByCategory(MEDIA_CATEGORY.VIDEOS);
}

/**
 * Returns all available media assets grouped by category.
 * @returns {{ images: object[], gifs: object[], videos: object[] }}
 */
export function listAllMedia() {
  return {
    images: listImages(),
    gifs:   listGifs(),
    videos: listVideos(),
  };
}
