/**
 * mediaManifest.js
 *
 * Static index of files present in the local media folders.
 * Generated automatically by running `npm run generate-media`.
 * Do not edit this file manually.
 *
 * Structure: { category: [fileName, ...] }
 */
import { MEDIA_CATEGORY } from './mediaTypes';

const mediaManifest = {
  [MEDIA_CATEGORY.IMAGES]: [
    'photo_2026-07-11_09-31-45.jpg',
  ],
  [MEDIA_CATEGORY.GIFS]: [
    'kling_20260710_Image_to_Video_Beauty_mat_5169_0.gif',
  ],
  [MEDIA_CATEGORY.VIDEOS]: [
    '0712(1).mp4',
    'kling_20260710_Image_to_Video__5122_0.mp4',
  ],
  regenerated: true,
  generatedAt: 1784919770251,
};

export default mediaManifest;
